name: "ci"

on:
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    name: Lint and test
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: ${{ matrix.go-version }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=30m -E gocritic

      - name: Run tests
        run: go test -v ./...
